version: '3.8'
services:
  security-txt:
    image: ghcr.io/utesgui/security.txt:latest
    environment:
      - SECURITY_STRING=${SECURITY_STRING}
      - SERVINGPATH=${SERVINGPATH:-/security.txt}
#    volumes:
#      - /opt/security-txt/public_html:/usr/share/nginx/html
#    ports:
#      - "80:80"
    networks:
      - proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - traefik.http.routers.security-txt.rule=Path(`${SERVINGPATH:-/security.txt}`)
      - "traefik.http.routers.security-txt.entrypoints=https,http"
      - "traefik.http.routers.security-txt.priority=420"
      - "traefik.http.routers.security-txt.tls.certresolver=le-tls" # le-dns, le-tls, le-http
      - "traefik.http.routers.security-txt.service=security-txt"
      - "traefik.http.services.security-txt.loadbalancer.server.port=80"
      - "traefik.http.services.security-txt.loadbalancer.server.scheme=http" # http, https, ...

networks:
  proxy:
    external: true